version: '3.6'

services:
  telegraf:
    container_name: telegraf-fritzbox4pi
    image: jenszech/telegraf-fritzbox4pi:latest
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
    ports:
      - "8092:8092/udp"
      - "8094:8094/tcp"
      - "8125:8125/udp"
    volumes:
      - ./volumes/telegraf:/etc/telegraf
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:

      default:
        driver: bridge
        ipam:
          driver: default